"""This file contains the paths to save the results of the program"""
one_task_patch = "save_dir/task_one"
two_task_patch = "save_dir/task_two"
three_task_patch = "save_dir/task_three"
four_task_patch = "save_dir/task_four"
five_task_patch = "save_dir/task_five"
six_task_patch = "save_dir/task_six"
seven_task_patch = "save_dir/task_seven"
eight_task_patch = "save_dir/task_eight"
