"""
This file contains the paths to the dataset files
"""
name_basics = "imdb-data/name.basics.tsv.gz"
title_basics = "imdb-data/title.basics.tsv.gz"
title_akas = "imdb-data/title.akas.tsv.gz"
title_crew = "imdb-data/title.crew.tsv.gz"
title_episode = "imdb-data/title.episode.tsv.gz"
title_principals = "imdb-data/title.principals.tsv.gz"
title_ratings = "imdb-data/title.ratings.tsv.gz"
